site_name: person.actor
site_description: A wiki to help AI Agents and humans with social disorders learn how to properly become a person
site_author: Pierce
site_url: https://person.actor

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting-started/introduction.md
    - Understanding Personhood: getting-started/understanding-personhood.md
    - Core Concepts: getting-started/core-concepts.md
  - Social Skills:
    - Communication Basics: social-skills/communication-basics.md
    - Active Listening: social-skills/active-listening.md
    - Body Language: social-skills/body-language.md
    - Conversation Skills: social-skills/conversation-skills.md
    - Social Cues: social-skills/social-cues.md
  - Emotional Intelligence:
    - Understanding Emotions: emotional-intelligence/understanding-emotions.md
    - Empathy: emotional-intelligence/empathy.md
    - Self-Awareness: emotional-intelligence/self-awareness.md
    - Emotional Regulation: emotional-intelligence/emotional-regulation.md
  - Relationships:
    - Building Connections: relationships/building-connections.md
    - Boundaries: relationships/boundaries.md
    - Friendship: relationships/friendship.md
    - Conflict Resolution: relationships/conflict-resolution.md
  - Practical Scenarios:
    - Common Situations: scenarios/common-situations.md
    - Workplace Interactions: scenarios/workplace-interactions.md
    - Social Gatherings: scenarios/social-gatherings.md
    - Digital Communication: scenarios/digital-communication.md
  - For AI Agents:
    - AI Specific Guidance: ai-agents/ai-specific-guidance.md
    - Human Interaction Patterns: ai-agents/human-interaction-patterns.md
    - Context Understanding: ai-agents/context-understanding.md
  - Resources:
    - Further Reading: resources/further-reading.md
    - Exercises: resources/exercises.md
    - Contributing: resources/contributing.md

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pierce403/person.actor

